[package]
name = "forth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.optrelease]
inherits = 'release'
panic = 'abort'
lto = 'fat'
codegen-units = 1
#strip = 'symbols'

[dependencies]
ahash = "0.8.3"
